/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package integradorfinanças.VIEW;

import integradorfinanças.CONEXAO.ConexaoDB;

/**
 *
 * @author bruno.costa2
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonInvestimentos = new javax.swing.JButton();
        jButtonMeta = new javax.swing.JButton();
        jButtonRelatorios = new javax.swing.JButton();
        jButtonGanhos = new javax.swing.JButton();
        jButtonGastosFixos = new javax.swing.JButton();
        jButtonGastosVariaveis = new javax.swing.JButton();
        jButtonFecharPrincipal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Olá \"X\"");

        jButtonInvestimentos.setText("INVESTIMENTOS");
        jButtonInvestimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInvestimentosActionPerformed(evt);
            }
        });

        jButtonMeta.setText("META");
        jButtonMeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMetaActionPerformed(evt);
            }
        });

        jButtonRelatorios.setText("RELATORIOS");
        jButtonRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatoriosActionPerformed(evt);
            }
        });

        jButtonGanhos.setText("GANHOS");
        jButtonGanhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGanhosActionPerformed(evt);
            }
        });

        jButtonGastosFixos.setText("GASTOS FIXOS");
        jButtonGastosFixos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGastosFixosActionPerformed(evt);
            }
        });

        jButtonGastosVariaveis.setText("GASTOS VARIAVEIS");
        jButtonGastosVariaveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGastosVariaveisActionPerformed(evt);
            }
        });

        jButtonFecharPrincipal.setText("Fechar");
        jButtonFecharPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharPrincipalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonGastosFixos, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonGastosVariaveis))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonInvestimentos, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonMeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonGanhos, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(250, 250, 250)
                                .addComponent(jLabel1)))
                        .addGap(0, 67, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonFecharPrincipal)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGastosFixos, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGanhos, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGastosVariaveis, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInvestimentos, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMeta, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jButtonFecharPrincipal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFecharPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharPrincipalActionPerformed
        dispose();
        
    }//GEN-LAST:event_jButtonFecharPrincipalActionPerformed

    private void jButtonGastosFixosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGastosFixosActionPerformed
        Gastos gastos = new Gastos();
        gastos.setVisible(true);
    }//GEN-LAST:event_jButtonGastosFixosActionPerformed

    private void jButtonGastosVariaveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGastosVariaveisActionPerformed
        GastosVariaveis gasVa = new GastosVariaveis();
        gasVa.setVisible(true);
    }//GEN-LAST:event_jButtonGastosVariaveisActionPerformed

    private void jButtonGanhosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGanhosActionPerformed
        Ganhos ganhos = new Ganhos();
        ganhos.setVisible(true);
    }//GEN-LAST:event_jButtonGanhosActionPerformed

    private void jButtonInvestimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInvestimentosActionPerformed
        Investimento invest = new Investimento();
        invest.setVisible(true);
    }//GEN-LAST:event_jButtonInvestimentosActionPerformed

    private void jButtonMetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMetaActionPerformed
        Meta meta = new Meta();
        meta.setVisible(true);
    }//GEN-LAST:event_jButtonMetaActionPerformed

    private void jButtonRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatoriosActionPerformed
        Relatorio relatorio = new Relatorio();
        relatorio.setVisible(true);
        ConexaoDB cdb = new ConexaoDB();
       
        
    }//GEN-LAST:event_jButtonRelatoriosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFecharPrincipal;
    private javax.swing.JButton jButtonGanhos;
    private javax.swing.JButton jButtonGastosFixos;
    private javax.swing.JButton jButtonGastosVariaveis;
    private javax.swing.JButton jButtonInvestimentos;
    private javax.swing.JButton jButtonMeta;
    private javax.swing.JButton jButtonRelatorios;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
