/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package integradorfinanças.VIEW;

import integradorfinanças.CONEXAO.ConexaoDB;
import integradorfinanças.MODEL.Ganho;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author bruno.costa2
 */
public class Relatorio extends javax.swing.JFrame {

    List<Ganho> listaGanhos;

    /**
     * Creates new form Relatorio
     */
    public Relatorio() {
        initComponents();
        try {
            exibirGanhos();
            atualizarMeta();
        } catch (SQLException e) {

        }
    }

    public void exibirGanhos() throws SQLException {
        ConexaoDB cDB = new ConexaoDB();
        listaGanhos = new ArrayList<Ganho>();
        ResultSet rs = cDB.buscarDados("ganhos");
        while (rs.next()) {
            Ganho ctn = new Ganho();
            ctn.setNomeganho(rs.getString("nomeganhos"));
            ctn.setValorganho(rs.getDouble("valorganhos"));
            ctn.setDataganhos(rs.getString("dataganhos"));
            //Assuming you have a user object            
            listaGanhos.add(ctn);
        }
        rs = cDB.buscarDados("gastosfixos");
        while (rs.next()) {
            Ganho ctn = new Ganho();
            ctn.setNomeganho("Gastos fixos");
            ctn.setValorganho(rs.getDouble("gastofixototal"));
            ctn.setDataganhos(" ");
            //Assuming you have a user object            
            listaGanhos.add(ctn);
        }
        rs = cDB.buscarDados("outrosgastosfixos");
        while (rs.next()) {
            Ganho ctn = new Ganho();
            ctn.setNomeganho(rs.getString("nomeogf"));
            ctn.setValorganho(rs.getDouble("valorogf"));
            ctn.setDataganhos(" ");
            //Assuming you have a user object            
            listaGanhos.add(ctn);
        }
        rs = cDB.buscarDados("gastosvariaveis");
        while (rs.next()) {
            Ganho ctn = new Ganho();
            ctn.setNomeganho(rs.getString("nomegv"));
            ctn.setValorganho(rs.getDouble("valorgv"));
            ctn.setDataganhos(rs.getString("datagv"));
            //Assuming you have a user object            
            listaGanhos.add(ctn);
        }
        rs = cDB.buscarDados("investimentos");
        while (rs.next()) {
            Ganho ctn = new Ganho();
            ctn.setNomeganho(rs.getString("nomeinv"));
            ctn.setValorganho(rs.getDouble("valorinv"));
            ctn.setDataganhos(rs.getString("datainv"));
            //Assuming you have a user object            
            listaGanhos.add(ctn);
        }

        for (int i = 0; i < listaGanhos.size(); i++) {
            jTableRelatorio.setValueAt(listaGanhos.get(i).getDataganhos(), i, 0);
            jTableRelatorio.setValueAt(listaGanhos.get(i).getNomeganho(), i, 1);
            jTableRelatorio.setValueAt(listaGanhos.get(i).getValorganho(), i, 2);
        }
    }
    
    public void atualizarMeta() throws SQLException {
        int progesso = 0;
        double meta = 0.0;
         ConexaoDB cDB = new ConexaoDB();
         ResultSet rs = cDB.buscarDados("metas");
         meta = rs.getDouble("valormetas");
        double soma = 0;
        for (int i = 0; i < listaGanhos.size(); i++) {            
            soma = soma + listaGanhos.get(i).getValorganho();
        }
        if (soma < meta) {
            //regra de tres setar progresso
            
            jProgressBar1.setValue(progesso);
        } else {
            jProgressBar1.setValue(100);
        }
    }

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRelatorio = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButtonOkRelatorio = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableRelatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Data", "Nome", "Valor"
            }
        ));
        jScrollPane1.setViewportView(jTableRelatorio);

        jLabel2.setText("RELATÓRIO");

        jButtonOkRelatorio.setText("OK");
        jButtonOkRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkRelatorioActionPerformed(evt);
            }
        });

        jLabel3.setText("Investimentos X Meta");

        jProgressBar1.setOrientation(1);
        jProgressBar1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jProgressBar1PropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jButtonOkRelatorio)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonOkRelatorio)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOkRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkRelatorioActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonOkRelatorioActionPerformed

    private void jProgressBar1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jProgressBar1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jProgressBar1PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Relatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOkRelatorio;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRelatorio;
    // End of variables declaration//GEN-END:variables
}
